kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: music-app-replicasets
  namespace: music-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: music-app

  template:
    metadata:
      labels:              # ✅ labels (plural)
        app: music-app
    spec:                  # ✅ pod spec inside template
      containers:
      - name: music-app
        image: ayushraturi/music-app:latest
        ports:
        - containerPort: 80

